{"name": "test_create_customer", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x00000250BE051AC0>\n\n    @allure.description(\"Test creating a customer via API.\")\n    def test_create_customer(self):\n        url = f\"{self.base_url}/customers\"\n        response = ApiRequests.post(url, json=self.customer_payload, headers=self.common_headers)\n>       assert response.status_code == 200, f\"Failed to create customer: {response.text}\"\nE       AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nE       assert 400 == 200\nE        +  where 400 = <Response [400]>.status_code\n\napi_test.py:73: AssertionError"}, "description": "Test creating a customer via API.", "attachments": [{"name": "[POST] request", "source": "fbd00e85-ae05-47b4-944b-e981b2759960-attachment.json", "type": "application/json"}, {"name": "response [400]", "source": "75492221-22c1-446c-bbc5-3a1fe65379cb-attachment.json", "type": "application/json"}], "start": 1708867843812, "stop": 1708867845429, "uuid": "d21b0816-96cd-45ec-a670-4a62b8040750", "historyId": "1689073ee40887eadd63d72aac5cf654", "testCaseId": "1689073ee40887eadd63d72aac5cf654", "fullName": "api_test.TestApi#test_create_customer", "labels": [{"name": "story", "value": "Customer Management"}, {"name": "feature", "value": "API Tests"}, {"name": "tag", "value": "api"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "6400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}