{"name": "test_create_customer", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x000001D1F7C845C0>\n\n    @allure.description(\"Test creating a customer via API.\")\n    def test_create_customer(self):\n        url = f\"{self.base_url}/customers\"\n        response = ApiRequests.post(url, json=self.customer_payload, headers=self.common_headers)\n>       assert response.status_code == 200, f\"Failed to create customer: {response.text}\"\nE       AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nE       assert 400 == 200\nE        +  where 400 = <Response [400]>.status_code\n\napi_test.py:73: AssertionError"}, "description": "Test creating a customer via API.", "attachments": [{"name": "[POST] request", "source": "2d2a915e-5ee7-45b7-98c2-8e903d1e3460-attachment.json", "type": "application/json"}, {"name": "response [400]", "source": "4f116a79-7a26-4e4d-9090-76d2799d8db2-attachment.json", "type": "application/json"}], "start": 1708866685369, "stop": 1708866687204, "uuid": "9a102b90-cc0c-49f0-8d5f-affe66d37cb4", "historyId": "1689073ee40887eadd63d72aac5cf654", "testCaseId": "1689073ee40887eadd63d72aac5cf654", "fullName": "api_test.TestApi#test_create_customer", "labels": [{"name": "feature", "value": "API Tests"}, {"name": "story", "value": "Customer Management"}, {"name": "tag", "value": "api"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "23112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}