{"name": "test_password_recovery_with_invalid_email", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Please enter a valid email address (Ex: johndoe@domain.com).' == 'If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).'\n  \n  - If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).\n  + Please enter a valid email address (Ex: johndoe@domain.com).", "trace": "self = <tests.login_test.TestLogin object at 0x00000252AC3F0B30>\n\n    def test_password_recovery_with_invalid_email(self):\n        login_page.click_forgot_password()\n        login_page.fill_email_address_reset(\"Benikun88gmail.com\")\n        login_page.click_reset_password()\n>       assert login_page.get_email_checkbox_error() == config_login.EXPECTED_PASSWORD_TEXTBOX_ERROR\nE       AssertionError: assert 'Please enter a valid email address (Ex: johndoe@domain.com).' == 'If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).'\nE         \nE         - If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).\nE         + Please enter a valid email address (Ex: johndoe@domain.com).\n\nlogin_test.py:69: AssertionError"}, "steps": [{"name": "enter to forgot password", "status": "passed", "start": 1708983812761, "stop": 1708983813775}, {"name": "fill the email address", "status": "passed", "parameters": [{"name": "email_recover", "value": "'Benikun88gmail.com'"}], "start": 1708983813775, "stop": 1708983813943}, {"name": "click on reset password", "status": "passed", "start": 1708983813943, "stop": 1708983814024}, {"name": "Retrieve email textbox error message", "status": "passed", "start": 1708983814024, "stop": 1708983814062}], "attachments": [{"name": "screenshot", "source": "33012bea-2351-4a5b-986d-dec35cad1033-attachment.png", "type": "image/png"}], "start": 1708983812761, "stop": 1708983814062, "uuid": "a19d43e0-9c47-4327-8ed5-e11ded21e02a", "historyId": "9539fefb321469cb043d933a175dc546", "testCaseId": "9539fefb321469cb043d933a175dc546", "fullName": "login_test.TestLogin#test_password_recovery_with_invalid_email", "labels": [{"name": "feature", "value": "Login"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "19320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_test"}]}