{"name": "test_create_customer", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nassert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.api_test.TestApi object at 0x0000024CABEA23C0>\n\n    def test_create_customer(self):\n        url = f\"{self.base_url}/customers\"\n        response = ApiRequests.post(url, json=self.customer_payload, headers=self.common_headers)\n>       assert response.status_code == 200, f\"Failed to create customer: {response.text}\"\nE       AssertionError: Failed to create customer: {\"message\":\"A customer with the same email address already exists in an associated website.\"}\nE       assert 400 == 200\nE        +  where 400 = <Response [400]>.status_code\n\napi_test.py:69: AssertionError"}, "attachments": [{"name": "[POST] request", "source": "f7a62a1e-b2ac-4c6e-94ce-7e5c5829de2c-attachment.json", "type": "application/json"}, {"name": "response [400]", "source": "b375c6b4-6462-4cf8-bcbd-a7c36493832d-attachment.json", "type": "application/json"}], "start": 1708858023864, "stop": 1708858025694, "uuid": "cc79ca1d-ad84-4114-b59b-dda66431225d", "historyId": "1689073ee40887eadd63d72aac5cf654", "testCaseId": "1689073ee40887eadd63d72aac5cf654", "fullName": "api_test.TestApi#test_create_customer", "labels": [{"name": "tag", "value": "api"}, {"name": "suite", "value": "api_test"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "5044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_test"}]}