{"name": "test_password_recovery_with_invalid_email", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Please enter a valid email address (Ex: johndoe@domain.com).' == 'If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).'\n  \n  - If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).\n  + Please enter a valid email address (Ex: johndoe@domain.com).", "trace": "self = <tests.login_test.TestLogin object at 0x000001E039D102C0>\n\n    def test_password_recovery_with_invalid_email(self):\n        login_page.click_forgot_password()\n        login_page.fill_email_address_reset(\"Benikun88gmail.com\")\n        login_page.click_reset_password()\n>       assert login_page.get_email_checkbox_error() == config_login.EXPECTED_PASSWORD_TEXTBOX_ERROR\nE       AssertionError: assert 'Please enter a valid email address (Ex: johndoe@domain.com).' == 'If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).'\nE         \nE         - If there is an account associated with Benikun88@gmail.com you will receive an email with a link to reset your password.Please enter a valid email address (Ex: johndoe@domain.com).\nE         + Please enter a valid email address (Ex: johndoe@domain.com).\n\nlogin_test.py:69: AssertionError"}, "steps": [{"name": "enter to forgot password", "status": "passed", "start": 1708983739098, "stop": 1708983740042}, {"name": "fill the email address", "status": "passed", "parameters": [{"name": "email_recover", "value": "'Benikun88gmail.com'"}], "start": 1708983740042, "stop": 1708983740243}, {"name": "click on reset password", "status": "passed", "start": 1708983740243, "stop": 1708983740316}, {"name": "Retrieve email textbox error message", "status": "passed", "start": 1708983740316, "stop": 1708983740364}], "attachments": [{"name": "screenshot", "source": "a8212c54-3428-4520-8ba0-bdf88c56952f-attachment.png", "type": "image/png"}], "start": 1708983739098, "stop": 1708983740365, "uuid": "4b3010b6-d4a8-4de0-a275-69b75c62169e", "historyId": "9539fefb321469cb043d933a175dc546", "testCaseId": "9539fefb321469cb043d933a175dc546", "fullName": "login_test.TestLogin#test_password_recovery_with_invalid_email", "labels": [{"name": "feature", "value": "Login"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-EV98OK4E"}, {"name": "thread", "value": "12492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_test"}]}